 apiVersion: v1
 kind: Service
 metadata:
    name: customer-np-srv
 spec:
    type: NodePort
    selector:
        app: customer-api-endpoint ##selecting internal app
    ports:
        - name: customer-api-endpoint
          protocol: TCP
          port: 80 ##port maps into MS
          targetPort: 8080 ##port of the MS